In [1]:
import numpy as np

# Homography

## Singular Value Decomposition

In [2]:
A = np.array([[1,2,3],
             [4,5,6]])
u, s, vh = np.linalg.svd(A)
print(u)
print(s)
print(vh)
# Find the singular Value Decomposition of data
# Tips: np.linalg.svd

[[-0.3863177   0.92236578]
 [-0.92236578 -0.3863177 ]]
[9.508032   0.77286964]
[[-0.42866713 -0.56630692 -0.7039467 ]
 [-0.80596391 -0.11238241  0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]


In [3]:
v = vh.T
A @ v[:, -1] # A @ vh[-1 , :]

array([ 2.22044605e-16, -4.44089210e-16])

## Feature Match

In [4]:
from scipy.spatial import distance

In [5]:
a = np.array([[4, 3],
              [5, 8],
              [4, 10],
              [10, 8]])
b = np.array([[10, 3],
              [5, 20],
              [4, 2]
              ])

In [6]:
# Find the distance of a and b   
d = distance.cdist(a, b)
print(d)

[[ 6.         17.02938637  1.        ]
 [ 7.07106781 12.          6.08276253]
 [ 9.21954446 10.04987562  8.        ]
 [ 5.         13.          8.48528137]]


In [7]:
# forward matching
idx = np.argsort(d, axis=1)
idx

array([[2, 0, 1],
       [2, 0, 1],
       [2, 0, 1],
       [0, 2, 1]])

In [8]:
fwd_match_res_no_ratio_test = np.array([[0, 2],
                                        [1, 2],
                                        [2, 2],
                                        [3, 0]])
fwd_match_res_no_ratio_test

array([[0, 2],
       [1, 2],
       [2, 2],
       [3, 0]])

In [9]:
np.take_along_axis(d, idx[:,0:1], axis=1)

array([[1.        ],
       [6.08276253],
       [8.        ],
       [5.        ]])

In [10]:
np.take_along_axis(d, idx[:,1:2], axis=1)

array([[6.        ],
       [7.07106781],
       [9.21954446],
       [8.48528137]])

In [11]:
ratio = np.take_along_axis(d, idx[:,0:1], axis=1) / np.take_along_axis(d, idx[:,1:2], axis=1)
ratio

array([[0.16666667],
       [0.86023253],
       [0.86772183],
       [0.58925565]])

In [12]:
fwd_match_res = np.array([[0, 2],
                          [3, 0]])
fwd_match_res

array([[0, 2],
       [3, 0]])

In [13]:
np.argsort(d, axis=0)

array([[3, 2, 0],
       [0, 1, 1],
       [1, 3, 2],
       [2, 0, 3]])

In [14]:
bkwd_match_res = np.array([[0, 2]])

In [15]:
set(map(tuple, fwd_match_res))

{(0, 2), (3, 0)}

In [16]:
intersect = set(map(tuple, fwd_match_res)) & set(map(tuple, bkwd_match_res))
intersect

{(0, 2)}

In [17]:
res = np.array(list(intersect))
res

array([[0, 2]])

## np.random.choice

In [18]:
num_pts = np.random.choice((10,10))
n = 5
rand_ind = np.random.choice(num_pts, n, replace=False)
print(rand_ind)

[2 4 5 8 1]
